import React from "react";

interface EulaContentProps {
  headingLevel?: 'h2' | 'h3';
  className?: string;
}

const EulaContent: React.FC<EulaContentProps> = ({ 
  headingLevel = 'h3', 
  className = "space-y-6 text-gray-700" 
}) => {
  const HeadingComponent = headingLevel;
  const headingClasses = headingLevel === 'h2' 
    ? "text-xl font-semibold text-gray-900 mb-3"
    : "text-xl font-semibold text-gray-900 mb-3";

  return (
    <div className={className}>
      <section>
        <HeadingComponent className={headingClasses}>
          Definitions
        </HeadingComponent>
        <p>
          For purposes of this Agreement, the following terms have the meanings set forth below:
          <ul className="list-disc pl-5 mt-2">
            <li><strong>"Adaptive AI" or "Company"</strong> means Adaptive AI LLC, a Nevada limited liability company with principal offices in Houston, Texas.</li>
            <li><strong>"Agreement"</strong> means this End User License Agreement.</li>
            <li><strong>"AI Technology"</strong> means any artificial intelligence, machine learning, natural language processing, or other automated decision-making technology integrated into the Services.</li>
            <li><strong>"Customer Data"</strong> means all data, content, and information that you or your users input, upload, or otherwise provide to the Services.</li>
            <li><strong>"Documentation"</strong> means the user guides, manuals, and technical documentation for the Services made available by Company.</li>
            <li><strong>"Services"</strong> means the software-as-a-service platform, agentic AI tools, and related services provided by Adaptive AI.</li>
            <li><strong>"User" or "you"</strong> means the individual or entity that has accepted this Agreement.</li>
          </ul>
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          1. License Grant and Scope
        </HeadingComponent>
        <p>
          Subject to your compliance with this Agreement, Company grants you a non-exclusive, non-transferable, revocable, limited license during the subscription term to:
          <ul className="list-disc pl-5 mt-2">
            <li>(a) Access and use the Services for your internal business purposes in accordance with the Documentation;</li>
            <li>(b) Allow your authorized users to access the Services under your account; and</li>
            <li>(c) Use any outputs generated by the AI Technology, subject to the restrictions herein.</li>
          </ul>
          This license does not grant you any rights to: (i) access or use the underlying software code, algorithms, or AI models; (ii) reverse engineer, decompile, or disassemble the Services; (iii) create derivative works based on the Services; or (iv) use the Services for any unlawful purpose or in violation of applicable laws.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          2. AI Technology and Data Rights
        </HeadingComponent>
        <p>
          <strong>2.1 AI-Generated Outputs</strong><br />
          Subject to the terms of this Agreement, you own the outputs generated by the AI Technology based on your inputs, except to the extent such outputs incorporate Company's pre-existing intellectual property or third-party content.
        </p>
        <p>
          <strong>2.2 Responsible AI Practices</strong><br />
          Company implements responsible AI practices including bias mitigation, transparency measures, and human oversight mechanisms. However, you acknowledge that AI systems may produce inaccurate, incomplete, or biased results and agree to implement appropriate review processes.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          3. User Responsibilities and Restrictions
        </HeadingComponent>
        <p>
          You are responsible for:
          <ul className="list-disc pl-5 mt-2">
            <li>(a) Maintaining the confidentiality and security of your account credentials;</li>
            <li>(b) All activities occurring under your account;</li>
            <li>(c) Ensuring your use complies with all applicable laws and regulations;</li>
            <li>(d) Implementing appropriate data backup and recovery procedures;</li>
            <li>(e) Reviewing AI-generated outputs for accuracy and appropriateness before use;</li>
            <li>(f) Complying with all AI governance and ethical use requirements applicable to your industry.</li>
          </ul>
          You may not:
          <ul className="list-disc pl-5 mt-2">
            <li>(a) Use the Services to violate any applicable law or regulation;</li>
            <li>(b) Interfere with or disrupt the Services or Company's systems;</li>
            <li>(c) Share account credentials or allow unauthorized access;</li>
            <li>(d) Input data that infringes third-party intellectual property rights;</li>
            <li>(e) Use the Services to develop competing AI products or services;</li>
            <li>(f) Attempt to extract, reverse engineer, or replicate the underlying AI models or algorithms.</li>
          </ul>
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          4. Intellectual Property
        </HeadingComponent>
        <p>
          <strong>4.1 Company IP</strong><br />
          The Services, including all software, AI models, algorithms, and Documentation, constitute Company's proprietary intellectual property or that of its licensors. No title or ownership rights are transferred to you under this Agreement.
        </p>
        <p>
          <strong>4.2 Customer IP</strong><br />
          You retain all rights in your Customer Data. By using the Services, you grant Company a limited license to process Customer Data solely to provide the Services and as described in this Agreement.
        </p>
        <p>
          <strong>4.3 Feedback</strong><br />
          Any feedback, suggestions, or improvements you provide regarding the Services may be used by Company without restriction or compensation.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          5. Service Level Agreement
        </HeadingComponent>
        <p>
          <strong>5.1 Uptime Commitment</strong><br />
          Company will use commercially reasonable efforts to maintain 99.5% uptime for the Services, measured monthly, excluding scheduled maintenance and circumstances beyond Company's control.
        </p>
        <p>
          <strong>5.2 Support</strong><br />
          Company will provide technical support during normal business hours (9 AM - 6 PM CST, Monday through Friday, excluding holidays). Support response times are: (i) Critical issues: 4 hours; (ii) High priority: 24 hours; (iii) Normal priority: 48 hours.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          6. Warranties and Disclaimers
        </HeadingComponent>
        <p>
          <strong>6.1 Limited Warranty</strong><br />
          Company warrants that the Services will perform substantially in accordance with the Documentation under normal use. This warranty does not apply to issues caused by misuse, modifications, or third-party integrations.
        </p>
        <p>
          <strong>6.2 Disclaimer</strong><br />
          EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. COMPANY DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND THOSE ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. COMPANY DOES NOT WARRANT THAT AI-GENERATED OUTPUTS WILL BE ACCURATE, COMPLETE, OR ERROR-FREE.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          7. Limitation of Liability
        </HeadingComponent>
        <p>
          <strong>7.1 Liability Cap</strong><br />
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY'S TOTAL LIABILITY ARISING FROM OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED THE LOWER OF: (I) THE FEES PAID BY YOU IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY; OR (II) ONE THOUSAND DOLLARS ($1,000).
        </p>
        <p>
          <strong>7.2 Excluded Damages</strong><br />
          IN NO EVENT SHALL COMPANY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, USE, OR GOODWILL, REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p>
          <strong>7.3 Exceptions</strong><br />
          The limitations in this Section 7 do not apply to: (i) Company's gross negligence or willful misconduct; (ii) violations of intellectual property rights; (iii) breaches of confidentiality obligations; (iv) data security breaches caused by Company's failure to implement reasonable security measures; or (v) Company's indemnification obligations.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          8. Indemnification
        </HeadingComponent>
        <p>
          <strong>8.1 Company Indemnification</strong><br />
          Company will defend, indemnify, and hold you harmless from third-party claims that the Services infringe a valid patent, copyright, or trademark, provided you promptly notify Company of such claims and cooperate in the defense. Company's obligations are subject to a liability cap of twenty-four (24) months of fees paid under this Agreement for IP-related claims.
        </p>
        <p>
          <strong>8.2 Customer Indemnification</strong><br />
          You will defend, indemnify, and hold Company harmless from claims arising from: (i) your use of the Services in violation of this Agreement; (ii) your Customer Data; (iii) your violation of applicable laws; or (iv) your modification of the Services.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          9. Term and Termination
        </HeadingComponent>
        <p>
          <strong>9.1 Term</strong><br />
          This Agreement commences when you first access the Services and continues until terminated in accordance with this Section.
        </p>
        <p>
          <strong>9.2 Termination for Cause</strong><br />
          Either party may terminate this Agreement immediately upon written notice if the other party materially breaches this Agreement and fails to cure such breach within thirty (30) days after written notice.
        </p>
        <p>
          <strong>9.3 Termination for Convenience</strong><br />
          Either party may terminate this Agreement at any time with thirty (30) days' written notice.
        </p>
        <p>
          <strong>9.4 Effect of Termination</strong><br />
          Upon termination: (i) your access to the Services will cease; (ii) you must cease all use of the Services and destroy all copies of Company materials; (iii) Company will delete Customer Data in accordance with Section 3.2; and (iv) accrued obligations will survive termination.
        </p>
        <p>
          <strong>9.5 Survival</strong><br />
          The following sections survive termination: Definitions, Intellectual Property, Warranties and Disclaimers, Limitation of Liability, Indemnification, and Governing Law.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          10. Compliance and Export Controls
        </HeadingComponent>
        <p>
          You agree to comply with all applicable laws, including export control laws and regulations. You represent that you are not located in, or a national of, any country subject to U.S. government embargo or designated as a "terrorist supporting" country, and that you are not on any U.S. government list of prohibited or restricted parties.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          11. Governing Law and Dispute Resolution
        </HeadingComponent>
        <p>
          <strong>11.1 Governing Law</strong><br />
          This Agreement shall be governed by and construed in accordance with the laws of the State of Nevada, without regard to conflict of law principles.
        </p>
        <p>
          <strong>11.2 Jurisdiction</strong><br />
          Any legal action or proceeding arising under this Agreement shall be brought exclusively in the federal or state courts located in Harris County, Texas, and the parties hereby consent to personal jurisdiction and venue therein.
        </p>
        <p>
          <strong>11.3 Alternative Dispute Resolution</strong><br />
          Before filing any lawsuit, the parties agree to attempt to resolve disputes through good faith negotiation for thirty (30) days. If unsuccessful, disputes may be resolved through binding arbitration under the Commercial Arbitration Rules of the American Arbitration Association.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          12. General Provisions
        </HeadingComponent>
        <p>
          <strong>12.1 Entire Agreement</strong><br />
          This Agreement constitutes the entire agreement between the parties and supersedes all prior agreements, understandings, and communications relating to the subject matter hereof.
        </p>
        <p>
          <strong>12.2 Amendments</strong><br />
          Company may update this Agreement from time to time by posting a revised version on its website. Material changes will be communicated with thirty (30) days' notice.
        </p>
        <p>
          <strong>12.3 Assignment</strong><br />
          You may not assign this Agreement without Company's prior written consent. Company may assign this Agreement to any affiliate or in connection with a merger, acquisition, or sale of all or substantially all of its assets.
        </p>
        <p>
          <strong>12.4 Severability</strong><br />
          If any provision of this Agreement is held unenforceable, the remainder shall remain in full force and effect.
        </p>
        <p>
          <strong>12.5 Force Majeure</strong><br />
          Neither party shall be liable for delays or failures in performance resulting from circumstances beyond its reasonable control.
        </p>
      </section>

      <section>
        <HeadingComponent className={headingClasses}>
          13. Contact Information
        </HeadingComponent>
        <p>
          For questions regarding this Agreement, please contact:<br />
          Adaptive AI LLC<br />
          Contact: Saum Mathur<br />
          Email: legal@adaptiveai.com<br />
          Address: Houston, Texas
        </p>
      </section>

      <div className="mt-8 pt-6 border-t border-gray-200">
        <p className="text-sm text-gray-500">
            Last updated: {new Date().toLocaleDateString()}
        </p>
      </div>
    </div>
  );
};

export default EulaContent;